feature/message-persistence
RealMQ/realmq-web-sdk pull request #2
Opened 2018-04-19 12:00 UTC by alrik

* Introduce message persistence resource for retrieving channel history.
* Generalize interface of persisted and pub/sub messages

2018-04-19 19:59 UTC, baranga approved these changes

2018-04-20 07:32 UTC, derlarsen requested changes

2018-04-20 07:32 UTC, derlarsen commented on lib/responses/message.js
> +  fromPersistece: function(params) {
Typo: `fromPersistence `

2018-04-20 08:42 UTC, alrik commented on lib/responses/message.js
> +  fromPersistece: function(params) {
Fixed.

2018-04-20 09:33 UTC, derlarsen approved these changes

2018-04-20 09:35 UTC, merged