Add support for custom client id postfixes
RealMQ/realmq-web-sdk pull request #7
Opened 2023-03-02 23:14 UTC by alrik

2023-03-07 12:31 UTC, baranga requested changes

2023-03-07 12:31 UTC, baranga commented on lib/get-client-id-postfix.js
> +  return '@realmq/web-sdk@%%SDK-VERSION%%@' + navigator.userAgent + '-' + generateRandomBytes();
**issue:** depending on the length of `navigator.userAgent` this may generate a postfix which results in a too long client id.
**suggestion:** cap the user agent part in length so a too long client id becomes unlikely or impossible.

2023-03-07 12:31 UTC, baranga commented on lib/realmq.js
> +
**issue:** commented out code left over from development
**suggestion:** remove this
```suggestion
```

2023-03-07 12:31 UTC, baranga commented on lib/realmq.js
> +    clientId: authToken + clientIdPostfix ? ':' + clientIdPostfix : ''
**issue:** Operator precedence causes troubles to quickly understand this statement.
**suggestion:** Add braces to avoid relying on operator precedence knowledge.
```suggestion
    clientId: authToken + (clientIdPostfix ? ':' + clientIdPostfix : '')
```

2023-03-09 23:10 UTC, alrik commented on lib/get-client-id-postfix.js
> +  return '@realmq/web-sdk@%%SDK-VERSION%%@' + navigator.userAgent + '-' + generateRandomBytes();
:+1:

2023-03-12 10:58 UTC, baranga approved these changes
:+1:

2023-03-12 11:03 UTC, merged